add iframe snipet
autifyhq/autify-javascript-snippets pull request #49
Opened 2023-05-26 09:24 UTC by iwk7273

I have created an article about JS snippets that click on elements in an Iframe. Please review this one.

created by iwakami (CSpE)

2023-05-29 02:05 UTC, ozakimami commented
@harokki 
Could you review the snippet??

2023-05-29 02:44 UTC, harokki requested changes

2023-05-29 02:44 UTC, harokki commented on content/en/snippets/others/click_element_in_iframe.md
> + * Locate the document in iframe
[nits] I think the element that can be taken at this point is [HTMLIFrameElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement), so "Locate the iframe" seems to be better.

2023-05-30 13:30 UTC, harokki commented on content/en/snippets/others/click_element_in_iframe.md
> + * Locate the document in iframe
@iwk7273 Thank you! Could you edit Japanese version as well? 🙏

2023-05-31 01:12 UTC, iwk7273 commented on content/en/snippets/others/click_element_in_iframe.md
> + * Locate the document in iframe
@harokki I forgot to edit ja varsion...
I modified the comment  "iframe内のdocumentを取得する" to " iframeを探す", is it Ok for you?

2023-05-31 01:15 UTC, harokki commented on content/en/snippets/others/click_element_in_iframe.md
> + * Locate the document in iframe
@iwk7273 
Thanks! LGTM!

2023-05-31 01:15 UTC, harokki approved these changes

2023-05-31 05:54 UTC, otoyo approved these changes
LGTM but a script can only access a `contentWindow` property when both pages belong to the same origin so I guess it is better to note that.
FYI: https://developer.mozilla.org/ja/docs/Web/HTML/Element/iframe#%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E6%93%8D%E4%BD%9C

2023-06-05 02:16 UTC, iwk7273 commented
> LGTM but a script can only access a `contentWindow` property when both pages belong to the same origin so I guess it is better to note that. FYI: https://developer.mozilla.org/ja/docs/Web/HTML/Element/iframe#%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E6%93%8D%E4%BD%9C

@otoyo Thank you for the review!
I will create a FAQ about the problems that occur with cross-origin.

2023-06-05 02:20 UTC, merged