Add snippets for double-click, right-click, and asserting if the element is checked
autifyhq/autify-javascript-snippets pull request #8
Opened 2020-08-31 07:11 UTC by meih

Add these three snippets to provide JS workaround for:
- Double-click
- Right-click (_contextmenu_, to be exact)
- Assert if the element is checked (since the _checked_ assertion on `<input type="radio">` is not supported yet on the recorder)

2020-08-31 07:35 UTC, macoril requested changes
intercom上でお願い済みですが、冒頭に、
「どういうときに使うスニペットか」
という説明を追加してください

2020-08-31 09:30 UTC, sotayamashita commented on snippets/double-click-element.js
> +element.dispatchEvent(doubleClickEvent);
以下のサンプルコードのようにモダンブラウザ用のコードがないですが問題ないでしょうか？
https://github.com/autifyhq/autify-javascript-snippets/blob/master/snippets/mouseover.js#L24-L38

2020-08-31 09:30 UTC, sotayamashita commented on snippets/right-click-element.js
> +element.dispatchEvent(rightClickEvent);
以下のサンプルコードのようにモダンブラウザ用のコードがないですが問題ないでしょうか？
https://github.com/autifyhq/autify-javascript-snippets/blob/master/snippets/mouseover.js#L24-L38

2020-08-31 09:37 UTC, macoril commented on snippets/double-click-element.js
> +element.dispatchEvent(doubleClickEvent);
@sotayamashita 
堀さんはJS詳しめだから上記のような指摘の仕方でも直せそうですが、
そうじゃなくてアドバイスをこいながら頑張るCSメンバーのが多いので、
「モダンブラウザ用にこう書き足してね」
ってレビューのほうが助かります。そうするとサムさんの工数がかかりそうですが 🙏

2020-08-31 15:42 UTC, sotayamashita commented on snippets/right-click-element.js
> +element.dispatchEvent(rightClickEvent);
@meih 
モダンブラウザとIE11両方に対応するコードを作成しましたので書き換えお願いします
検証用サイト：https://swisnl.github.io/jQuery-contextMenu/demo.html
```
var event;
if (typeof(Event) === 'function') {
   /**
    * For modern browser
    * モダンブラウザの場合 
    */
   event = new MouseEvent("contextmenu", {"bubbles":true, "cancelable":true})
} else {
   /** 
    * For IE 11
    * IE 11 の場合
    */
   event = document.createEvent('MouseEvents');
   event.initEvent('contextmenu', true, true);
}
/* Fire a right-click event
 * 右クリックのイベントを発火させる */
element.dispatchEvent(event);  
```

2020-08-31 15:46 UTC, sotayamashita commented on snippets/double-click-element.js
> +element.dispatchEvent(doubleClickEvent);
@macoril 
> 「モダンブラウザ用にこう書き足してね」ってレビューのほうが助かります。
承知しました :+1:

@meih 
モダンブラウザとIE11両方に対応するコードを作成しましたので書き換えお願いします
検証用サイト：https://www.plus2net.com/jquery/msg-demo/event-dblclick2.php
```js
var event;
if (typeof(Event) === 'function') {
   /**
    * For modern browser
    * モダンブラウザの場合 
    */
   event = new MouseEvent("dblclick", {"bubbles":true, "cancelable":true})
} else {
   /** 
    * For IE 11
    * IE 11 の場合
    */
   event = document.createEvent('MouseEvents');
   event.initEvent('dblclick', true, true);
}
/* Fire a double-click event
 * ダブルクリックのイベントを発火させる */
element.dispatchEvent(event);  
```

2020-08-31 15:54 UTC, sotayamashita approved these changes

2020-08-31 23:59 UTC, meih commented on snippets/right-click-element.js
> +element.dispatchEvent(rightClickEvent);
@sotayamashita 
おお、今日やろうと思ったらもうUpdateいただいている...！ ありがとうございます。
@macoril さん指摘の冒頭コメント追加については、これベースに本日対応しますね。

2020-09-01 09:09 UTC, meih commented
@macoril cc @sotayamashita 
各スニペット冒頭に

- どういうときに使うスニペットか
- ユーザーが指定する値はどれで、何を指定するか

あたりの情報をコメント追記しましたので、ご確認をお願いします！

特に assert-checked.js は現状ラジオボタン用のワークアラウンドである反面いろいろ書いているので、余分だと思われる記述があれば省きますので仰ってくださいー。

2020-09-01 18:11 UTC, macoril commented on snippets/double-click-element.js
> +element.dispatchEvent(doubleClickEvent);
@sotayamashita 
めっちゃありがとうございます!
すごくたすかります❤️

2020-09-01 18:51 UTC, macoril commented
@meih 
完璧ですー！
ありがとうございます！

2020-09-01 18:51 UTC, merged